### ISSUE TITLE
Partition is read-only

### ISSUE THREAD

**Issue by 0xVZ** [queso-fuego/UEFI-GPT-image-creator#2]
Hey, i was following the UEFI dev series, and i implemented a stdlib-like file io abstraction, the problem is that every time i try to write a file, i always get a error (even when im passing EFI_FILE_MODE_CREATE).
And i believe its becouse write_gpt.exe creates the image with read-only attributes and i would like to know if it would be possible to make that optional.

This is the line that fails, i tried creating the file at Root ('), at EFI ('/EFI/') and at BOOT ('/EFI/BOOT/') same error.
`status = root->Open(root, ptr, path, EFI_FILE_MODE_WRITE | EFI_FILE_MODE_CREATE, 0);`

**Comment by queso-fuego** [comment]
The image itself has rw as permissions when using `ls -l`, and when the image is made from write_gpt it's opened with `wb+` which is read/write. There aren't any flags to set read/write permissions per GPT partition in the partition tables, either. So I'm not sure how it would be read only.

From looking at the EFI_FILE_PROTOCOL.Open() section of the UEFI specification, 13.5.2 in version 2.10, the OpenMode is only valid for Read, Read/Write, or Create/Read/Write. 

Using Create/Write is not one of those 3, maybe that's why it's erroring for you?

From the spec, bolded/italicized the OpenMode wording:
13.5.2 EFI_FILE_PROTOCOL.Open()
Summary
Opens a new file relative to the source file’s location.
Prototype
```
typedef
EFI_STATUS
(EFIAPI *EFI_FILE_OPEN) (
    IN EFI_FILE_PROTOCOL *This,
    OUT EFI_FILE_PROTOCOL **NewHandle,
    IN CHAR16 *FileName,
    IN UINT64 OpenMode,
    IN UINT64 Attributes
);
```

Parameters
This A pointer to the EFI_FILE_PROTOCOL instance that is the file handle to the source location. This would
typically be an open handle to a directory. See the type EFI_FILE_PROTOCOL description.
NewHandle A pointer to the location to return the opened handle for the new file.
See the type
EFI_FILE_PROTOCOL description.
FileName The Null-terminated string of the name of the file to be opened. The file name may contain the following
path modifiers: “", “.”, and “..”.
**_OpenMode The mode to open the file. The only valid combinations that the file may be opened with are: Read,
Read/Write, or Create/Read/Write. See “Related Definitions” below._**
